export const uiCopy = {
  en: {
    appSubtitle: "PHASE 1 / SUPERVISED RUNTIME",
    metric: {
      acceleration: "ACCELERATION",
      activeOps: "ACTIVE OPS",
      alphaState: "ALPHA STATE",
      available: "AVAILABLE",
      blocked: "BLOCKED",
      candidates: "CANDIDATES",
      coreHealth: "CORE HEALTH",
      deleted: "DELETED",
      downloadable: "DOWNLOADABLE",
      failure: "FAILURE",
      fixture: "FIXTURE",
      gpuCount: "GPU COUNT",
      inference: "INFERENCE",
      inspector: "INSPECTOR",
      installable: "INSTALLABLE",
      intent: "INTENT",
      intentRouter: "INTENT ROUTER",
      loaded: "LOADED",
      localModels: "LOCAL MODELS",
      manifests: "MANIFESTS",
      memory: "MEMORY",
      memoryAlpha: "MEMORY ALPHA",
      micCapture: "MIC CAPTURE",
      micPermission: "MIC PERMISSION",
      ocr: "OCR",
      ocrBlocks: "OCR BLOCKS",
      ocrOps: "OCR OPS",
      ocrText: "OCR TEXT",
      operations: "OPERATIONS",
      probe: "PROBE",
      probeDims: "PROBE DIMS",
      providers: "PROVIDERS",
      reason: "REASON",
      reranked: "RERANKED",
      reranker: "RERANKER",
      rerankOps: "RERANK OPS",
      required: "REQUIRED",
      resourceLeases: "RESOURCE LEASES",
      resourceMem: "RESOURCE MEM",
      resourceVram: "RESOURCE VRAM",
      rollback: "ROLLBACK",
      route: "ROUTE",
      runtimeMode: "RUNTIME MODE",
      sequence: "SEQUENCE",
      session: "SESSION",
      topDoc: "TOP DOC",
      tracked: "TRACKED",
      transport: "TRANSPORT",
      vectorDims: "VECTOR DIMS",
      vectors: "VECTORS",
      voiceEngine: "VOICE ENGINE",
      voiceFrames: "VOICE FRAMES",
      voiceMode: "VOICE MODE",
      voicePeak: "VOICE PEAK",
      voiceRms: "VOICE RMS",
    },
    value: {
      hidden: "hidden",
      shown: "shown",
    },
    connection: {
      connecting: "CONNECTING",
      online: "ONLINE",
      offline: "OFFLINE",
    },
    nav: {
      conversation: "Conversation",
      tasks: "Tasks",
      plugins: "Plugins",
      memory: "Memory",
      voice: "Voice",
      activity: "Activity",
      developer: "Developer",
      settings: "Settings",
    },
    view: {
      primarySession: "Primary Session",
      tasks: "Tasks",
      plugins: "Plugin Management",
      memoryCenter: "User Memory",
      voiceConsole: "Voice Console",
      developer: "Developer",
      settings: "Settings",
      activity: "Activity",
    },
    settings: {
      language: "Language",
      languageCurrent: "Current UI language",
      languageChanged: "Language changed",
      theme: "Theme",
      themeCurrent: "Current skin theme",
      themeChanged: "Theme changed",
      themeSchema: "Theme Schema",
      themeStorage: "Local persistence",
      themeRecovery: "Default recovery",
      themeSafe: "No executable skin code",
      signalTheme: "Signal",
      harborTheme: "Harbor",
      emberTheme: "Ember",
      english: "EN",
      chinese: "中文",
      general: "General",
      commandRouter: "Command Router",
      chatAnswer: "Chat Answer",
      voice: "Voice",
      memoryAlpha: "Memory Alpha",
      modelGovernance: "Model Governance",
      advanced: "Advanced",
      voiceSettings: "Voice Settings",
      ttsSettings: "TTS Settings",
    },
    action: {
      running: "running",
      complete: "complete",
      failed: "failed",
      settingsViewActive: "Settings view active",
      viewActive: "view active",
      conversationAlreadyActive: "Conversation already active",
      conversationSelected: "Conversation selected",
      typeCommandFirst: "Type a command first",
      commandSent: "Command sent",
      noConversationSelected: "No conversation selected",
      enterConversationTitle: "Enter a conversation title",
      conversationRenamed: "Conversation renamed",
      conversationRenameCancelled: "Conversation rename cancelled",
      renameModeActive: "Rename mode active",
      conversationCreated: "Conversation created",
      pluginManagementRefreshed: "Plugin status refreshed",
      memorySnapshotExported: "Memory snapshot exported",
      memorySnapshotImported: "Memory snapshot imported",
      pasteMemorySnapshotFirst: "Paste memory snapshot JSON first",
      enterRecallProbeFirst: "Enter recall probe text first",
      memoryAlphaRecallProbeComplete: "Memory alpha recall probe complete",
      memoryAlphaIs: "Memory alpha is",
      memoryAlphaDisabled: "Memory alpha disabled",
      fixtureEmbeddingUnavailable: "Fixture embedding provider unavailable",
      fixtureIntentUnavailable: "Fixture intent router unavailable",
      fixtureOcrUnavailable: "Fixture OCR provider unavailable",
      fixtureRerankerUnavailable: "Fixture reranker unavailable",
      fixtureEmbeddingCompleted: "Fixture embedding completed",
      fixtureIntentCompleted: "Fixture intent routing completed",
      fixtureOcrCompleted: "Fixture OCR completed",
      fixtureRerankerCompleted: "Fixture reranker completed",
      inspectorHidden: "Inspector hidden",
      inspectorShown: "Inspector shown",
      voiceSettingsOpened: "Voice settings opened",
      ttsSettingsOpened: "TTS settings opened",
      commandRouterProductModeRefreshed: "Command Router mode refreshed",
      commandRouterProductModeChanged: "Command Router mode changed",
      chatAnswerProductModeRefreshed: "Chat Answer mode refreshed",
      chatAnswerProductModeChanged: "Chat Answer mode changed",
      memoryAlphaRefreshed: "Memory alpha refreshed",
      userMemoryDeleted: "User memory deleted",
      userMemoryRefreshed: "User memory refreshed",
      modelGovernanceRefreshed: "Model governance refreshed",
    },
    label: {
      protocol: "PROTOCOL V1",
      localContract: "LOCAL CONTRACT",
      developerMode: "Developer Mode",
      evaluationCapability: "Evaluation capability",
      productSurface: "Product surface",
      readyDiagnostics: "Ready for developer-alpha diagnostics.",
      noLocalConversations: "No local conversations yet.",
      runtimeReady:
        "Runtime ready. Typed contracts are active and the renderer snapshot is synchronized.",
      noCoreTasks: "No Core tasks are currently registered.",
      noModelOperations: "No model lifecycle operations are visible.",
      noPlugins: "No bundled or local plugin manifests are visible.",
      pluginSafetySummary:
        "Local plugin discovery is list-only. Unknown plugin code remains disabled.",
      pluginThirdPartyDefault: "Third-party execution",
      pluginCodeExecution: "Unknown code execution",
      pluginMarketplace: "Marketplace access",
      pluginCapabilities: "Capabilities",
      pluginPermissions: "Permissions",
      pluginPermissionGate: "Permission gate",
      pluginDeclaredRisk: "Declared risk",
      pluginEffectiveRisk: "Effective risk",
      pluginConfirmationPolicy: "Confirmation",
      pluginExecutionMode: "Execution mode",
      pluginRouteSelectable: "Route selectable",
      pluginRuntime: "Runtime",
      pluginVersion: "Version",
      pluginStatePersistence: "State persistence",
      pluginStateToggle: "Local state",
      noTranscript: "No transcript captured in this session.",
      diagnostics: "Diagnostics",
      recentEvents: "Recent Events",
      events: "EVENTS",
      runtimeActivity: "Runtime Activity",
      runtimeActivitySubtitle: "supervisor + core event stream",
      memorySnapshot: "Memory Snapshot",
      waitingForCoreEvents: "Waiting for Core events.",
      pushToTalk: "Push to talk",
      toggleInspector: "Toggle inspector",
      hideInspector: "Hide inspector",
      showInspector: "Show inspector",
      generalSettings: "General settings",
      sendCommand: "Send command",
      commandPlaceholder: "Message Jarvis",
      recallProbePlaceholder: "Recall probe",
      memorySnapshotPlaceholder: "Memory snapshot JSON",
      agentCore: "AGENT CORE",
      voiceTranscript: "VOICE TRANSCRIPT",
      local: "LOCAL",
      inspector: "Inspector",
      probe: "Probe",
      brainDispatch: "Brain Dispatch",
      brainSource: "Source",
      brainIntent: "Intent",
      brainConfidence: "Confidence",
      brainStatus: "Status",
      brainPlan: "Plan",
      voiceService: "Voice Service",
      ttsService: "Cloud TTS",
      voiceRecognitionLanguage: "Recognition Language",
      voiceServiceConfigured: "Configured",
      voiceServiceMissing: "Not configured",
      voiceLanguageMismatch:
        "Voice recognition is set to English. Chinese commands may be misrecognized.",
      textOnlyAcceptance:
        "Text-only acceptance mode. Voice input is unavailable in this window.",
    },
    voiceCaptureNotice: {
      captureUnavailable: "Microphone capture could not start.",
      coreOffline: "Core is offline; microphone capture cannot start.",
      interrupted: "Microphone start was interrupted.",
      microphoneUnavailable: "Windows microphone capture could not start.",
      permissionDenied: "Windows microphone permission was denied.",
      voiceModeUnavailable:
        "Voice service could not enter PTT mode. Check provider credentials and network access.",
      voiceSessionUnavailable:
        "Voice service could not start a PTT session. Check Xunfei settings and service connectivity.",
    },
  },
  zh: {
    appSubtitle: "阶段 1 / 受监督本地运行时",
    metric: {
      acceleration: "加速后端",
      activeOps: "活跃操作",
      alphaState: "Alpha 状态",
      available: "可用",
      blocked: "受阻",
      candidates: "候选模型",
      coreHealth: "核心状态",
      deleted: "已删除",
      downloadable: "可下载",
      failure: "失败分类",
      fixture: "夹具",
      gpuCount: "GPU 数量",
      inference: "推理",
      inspector: "状态栏",
      installable: "可安装",
      intent: "意图",
      intentRouter: "意图路由",
      loaded: "已加载",
      localModels: "本地模型",
      manifests: "清单",
      memory: "Memory",
      memoryAlpha: "Memory Alpha",
      micCapture: "麦克风采集",
      micPermission: "麦克风权限",
      ocr: "OCR",
      ocrBlocks: "OCR 块",
      ocrOps: "OCR 操作",
      ocrText: "OCR 文本",
      operations: "操作",
      probe: "探测",
      probeDims: "探测维度",
      providers: "Provider",
      reason: "原因",
      reranked: "重排结果",
      reranker: "重排器",
      rerankOps: "重排操作",
      required: "必需配置",
      resourceLeases: "资源租约",
      resourceMem: "内存资源",
      resourceVram: "显存资源",
      rollback: "回滚",
      route: "路由",
      runtimeMode: "运行模式",
      sequence: "序列",
      session: "会话",
      topDoc: "首位文档",
      tracked: "已跟踪",
      transport: "传输",
      vectorDims: "向量维度",
      vectors: "向量",
      voiceEngine: "语音引擎",
      voiceFrames: "语音帧",
      voiceMode: "语音模式",
      voicePeak: "语音峰值",
      voiceRms: "语音 RMS",
    },
    value: {
      hidden: "隐藏",
      shown: "显示",
    },
    connection: {
      connecting: "连接中",
      online: "在线",
      offline: "离线",
    },
    nav: {
      conversation: "对话",
      tasks: "任务",
      plugins: "插件",
      memory: "记忆",
      voice: "语音",
      activity: "活动",
      developer: "开发者",
      settings: "设置",
    },
    view: {
      primarySession: "主会话",
      tasks: "任务",
      plugins: "插件管理",
      memoryCenter: "用户记忆",
      voiceConsole: "语音控制台",
      developer: "开发者",
      settings: "设置",
      activity: "活动",
    },
    settings: {
      language: "语言",
      languageCurrent: "当前界面语言",
      languageChanged: "语言已切换",
      theme: "皮肤主题",
      themeCurrent: "当前主题",
      themeChanged: "主题已切换",
      themeSchema: "主题 Schema",
      themeStorage: "本地持久化",
      themeRecovery: "默认恢复",
      themeSafe: "不执行皮肤代码",
      signalTheme: "Signal",
      harborTheme: "Harbor",
      emberTheme: "Ember",
      english: "EN",
      chinese: "中文",
      general: "通用",
      commandRouter: "Command Router",
      chatAnswer: "Chat Answer",
      voice: "语音",
      memoryAlpha: "记忆功能",
      modelGovernance: "模型治理",
      voiceSettings: "语音设置",
    },
    action: {
      running: "执行中",
      complete: "已完成",
      failed: "失败",
      settingsViewActive: "设置视图已打开",
      viewActive: "视图已打开",
      conversationAlreadyActive: "当前已经是这个会话",
      conversationSelected: "会话已切换",
      typeCommandFirst: "请先输入命令",
      commandSent: "命令已发送",
      noConversationSelected: "未选中会话",
      enterConversationTitle: "请输入会话标题",
      conversationRenamed: "会话已重命名",
      conversationRenameCancelled: "已取消重命名",
      renameModeActive: "重命名模式已打开",
      conversationCreated: "会话已创建",
      pluginManagementRefreshed: "插件状态已刷新",
      memorySnapshotExported: "记忆快照已导出",
      memorySnapshotImported: "记忆快照已导入",
      pasteMemorySnapshotFirst: "请先粘贴记忆快照 JSON",
      enterRecallProbeFirst: "请先输入回忆测试文本",
      memoryAlphaRecallProbeComplete: "记忆回忆测试已完成",
      memoryAlphaIs: "记忆功能当前状态为",
      memoryAlphaDisabled: "记忆功能已关闭",
      fixtureEmbeddingUnavailable: "Fixture embedding provider 不可用",
      fixtureIntentUnavailable: "Fixture intent router 不可用",
      fixtureOcrUnavailable: "Fixture OCR provider 不可用",
      fixtureRerankerUnavailable: "Fixture reranker 不可用",
      fixtureEmbeddingCompleted: "Fixture embedding 已完成",
      fixtureIntentCompleted: "Fixture intent routing 已完成",
      fixtureOcrCompleted: "Fixture OCR 已完成",
      fixtureRerankerCompleted: "Fixture reranker 已完成",
      inspectorHidden: "Inspector 已隐藏",
      inspectorShown: "Inspector 已显示",
      voiceSettingsOpened: "语音设置已打开",
      commandRouterProductModeRefreshed: "Command Router mode refreshed",
      commandRouterProductModeChanged: "Command Router mode changed",
      chatAnswerProductModeRefreshed: "Chat Answer mode refreshed",
      chatAnswerProductModeChanged: "Chat Answer mode changed",
      memoryAlphaRefreshed: "记忆功能已刷新",
      userMemoryDeleted: "用户记忆已删除",
      userMemoryRefreshed: "用户记忆已刷新",
      modelGovernanceRefreshed: "模型治理已刷新",
    },
    label: {
      protocol: "协议 V1",
      localContract: "本地契约",
      readyDiagnostics: "开发者 Alpha 诊断已就绪。",
      noLocalConversations: "还没有本地会话。",
      runtimeReady: "运行时已就绪。类型契约已启用，渲染器快照已同步。",
      noCoreTasks: "当前没有 Jarvis 任务。",
      noModelOperations: "当前没有可见的模型生命周期操作。",
      noPlugins: "当前没有可见的内置或本地插件。",
      pluginSafetySummary: "本地插件发现仅用于列出状态。未知插件代码保持禁用。",
      pluginThirdPartyDefault: "第三方执行",
      pluginCodeExecution: "未知代码执行",
      pluginMarketplace: "插件市场访问",
      pluginCapabilities: "能力",
      pluginPermissions: "权限",
      pluginPermissionGate: "权限门控",
      pluginDeclaredRisk: "声明风险",
      pluginEffectiveRisk: "有效风险",
      pluginConfirmationPolicy: "确认策略",
      pluginExecutionMode: "执行模式",
      pluginRouteSelectable: "可被路由选择",
      pluginRuntime: "运行时",
      pluginVersion: "版本",
      pluginStatePersistence: "State persistence",
      pluginStateToggle: "Local state",
      noTranscript: "当前会话还没有语音转写。",
      diagnostics: "诊断",
      recentEvents: "最近事件",
      events: "事件",
      runtimeActivity: "运行活动",
      runtimeActivitySubtitle: "supervisor + core 事件流",
      memorySnapshot: "Memory 快照",
      waitingForCoreEvents: "正在等待 Core 事件。",
      pushToTalk: "按住说话",
      toggleInspector: "切换 Inspector",
      hideInspector: "隐藏 Inspector",
      showInspector: "显示 Inspector",
      generalSettings: "通用设置",
      sendCommand: "发送命令",
      commandPlaceholder: "向 Jarvis 发送消息",
      recallProbePlaceholder: "回忆测试",
      memorySnapshotPlaceholder: "记忆快照 JSON",
      agentCore: "Jarvis",
      voiceTranscript: "语音转写",
      local: "本地",
      inspector: "Inspector",
      probe: "Probe",
      brainDispatch: "主脑派发",
      brainSource: "来源",
      brainIntent: "意图",
      brainConfidence: "置信度",
      brainStatus: "状态",
      brainPlan: "计划",
      voiceService: "语音服务",
      ttsService: "云端语音播报",
      voiceRecognitionLanguage: "识别语言",
      voiceServiceConfigured: "已配置",
      voiceServiceMissing: "未配置",
      voiceLanguageMismatch: "语音识别当前是 English，中文口令可能会被误识别。",
      textOnlyAcceptance: "文字验收模式：当前窗口不可用语音输入。",
    },
    voiceCaptureNotice: {
      captureUnavailable: "麦克风采集无法启动。",
      coreOffline: "Core 离线，无法启动麦克风采集。",
      interrupted: "麦克风启动已被中断。",
      microphoneUnavailable: "Windows 麦克风采集无法启动。",
      permissionDenied: "Windows 麦克风权限被拒绝。",
      voiceModeUnavailable:
        "语音服务无法进入 PTT 模式。请检查服务凭证和网络连接。",
      voiceSessionUnavailable:
        "语音服务无法启动 PTT 会话。请检查讯飞设置和服务连通性。",
    },
  },
} as const;

export const stage5Copy = {
  en: {
    title: "Product Alpha",
    history: "Session history",
    historyEmpty: "No structured session entries yet.",
    clearHistory: "Clear history",
    memoryContext: "Memory context",
    retry: "Retry",
    rollback: "Rollback view",
    tts: "Local result playback",
    ttsEnabled: "Enabled",
    ttsDisabled: "Disabled",
    play: "Play result",
    stop: "Stop playback",
    ttsUnavailable: "Local playback unavailable",
    safety: "Safety path",
    currentResult: "Current result",
    readOnly: "read-only",
    preserved: "preserved",
    blocked: "blocked",
    noTool: "no tool",
  },
  zh: {
    title: "产品 Alpha",
    history: "本次会话历史",
    historyEmpty: "当前还没有脱敏的会话记录。",
    clearHistory: "清空历史",
    memoryContext: "Memory 上下文",
    retry: "重试",
    rollback: "回滚视图",
    tts: "本地结果播报",
    ttsEnabled: "已开启",
    ttsDisabled: "已关闭",
    play: "播报结果",
    stop: "停止播报",
    ttsUnavailable: "本地播报不可用",
    safety: "安全路径",
    currentResult: "当前结果",
    readOnly: "只读",
    preserved: "已保留",
    blocked: "已阻止",
    noTool: "未选择工具",
  },
} as const;
