// Test-only safe projection; private launch binding is never part of this object.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const STAGES=Object.freeze(['controller_started','ownership_validated','targets_resolved','pre_kill_identity_verified','target_handles_opened','protected_baseline_captured','termination_started','main_signal_attempted','main_exit_waited','corehost_signal_attempted','corehost_exit_waited','child_signal_attempted','child_exit_waited','target_exit_verified','descendant_check_completed','protected_postcheck_completed','receipt_published','controller_completed']);
const ROLES=Object.freeze(['main','corehost','renderer','utility']);
const COUNTS=Object.freeze(['resolved','identityVerified','handleOpened','alreadyExited','killAttempted','killReturned','exitWaitStarted','exitObserved','waitTimedOut','handleError','killError','identityUnavailable','residualMatching']);
const FAILURES=Object.freeze(['pre_kill_identity_failed','target_set_incomplete','handle_open_failed','handle_state_failed','kill_call_failed','exit_wait_timeout','residual_target_detected','descendant_query_failed','residual_descendant_detected','protected_baseline_failed','protected_process_missing','receipt_write_failed','controller_budget_exhausted','result_ownership_failed','unexpected_controller_error']);
const exact=(o,keys)=>o&&typeof o==='object'&&!Array.isArray(o)&&Object.keys(o).sort().join()===keys.slice().sort().join();
function empty(){return {schemaVersion:1,lastReachedStage:STAGES[0],executed:false,allTerminationCallsCompleted:false,allTargetsExited:false,protectedSetPreserved:false,descendantCheckPassed:false,roleCounters:Object.fromEntries(ROLES.map(r=>[r,Object.fromEntries(COUNTS.map(c=>[c,0]))])),primaryFailure:null,cleanupOutcome:'not_started',totalDurationBucket:'under_5s'};}
function valid(r){return exact(r,Object.keys(empty()))&&r.schemaVersion===1&&STAGES.includes(r.lastReachedStage)&&['executed','allTerminationCallsCompleted','allTargetsExited','protectedSetPreserved','descendantCheckPassed'].every(k=>typeof r[k]==='boolean')&&exact(r.roleCounters,ROLES)&&ROLES.every(role=>exact(r.roleCounters[role],COUNTS)&&COUNTS.every(k=>Number.isInteger(r.roleCounters[role][k])&&r.roleCounters[role][k]>=0&&r.roleCounters[role][k]<=16))&&(r.primaryFailure===null||exact(r.primaryFailure,['category','stage'])&&FAILURES.includes(r.primaryFailure.category)&&STAGES.includes(r.primaryFailure.stage))&&['not_started','completed','incomplete'].includes(r.cleanupOutcome)&&['under_5s','5_to_10s','10_to_15s','deadline_reached'].includes(r.totalDurationBucket);}
function passed(r){return valid(r)&&!r.primaryFailure&&r.allTerminationCallsCompleted&&r.allTargetsExited&&r.protectedSetPreserved&&r.descendantCheckPassed&&r.roleCounters.main.resolved===1&&ROLES.every(role=>{const c=r.roleCounters[role];return c.identityVerified===c.resolved&&c.handleOpened===c.resolved&&c.exitObserved===c.resolved&&c.killReturned<=c.killAttempted&&c.killReturned+c.alreadyExited===c.resolved&&['waitTimedOut','handleError','killError','identityUnavailable','residualMatching'].every(k=>c[k]===0);});}
function advance(r,stage){if(!STAGES.includes(stage)||STAGES.indexOf(stage)<STAGES.indexOf(r.lastReachedStage))throw Error('SAFE_STAGE');r.lastReachedStage=stage;}
function fail(r,category){if(!r.primaryFailure)r.primaryFailure=Object.freeze({category:FAILURES.includes(category)?category:'unexpected_controller_error',stage:r.lastReachedStage});}
const hash=r=>crypto.createHash('sha256').update(JSON.stringify(r)).digest('hex');
function bindingValid(b){return exact(b,['scenario','owner','launch'])&&['B','controller_selftest'].includes(b.scenario)&&['owner','launch'].every(k=>typeof b[k]==='string'&&/^[a-f0-9]{32}$/.test(b[k]));}
function publish(directory,binding,receipt){if(!bindingValid(binding)||!valid(receipt))throw Error('SAFE_RECEIPT');const file=path.join(directory,'controller-receipt.json'),pending=file+'.pending';const envelope={schemaVersion:1,binding,receipt,digest:hash(receipt)};const fd=fs.openSync(pending,'wx',0o600);try{fs.writeFileSync(fd,JSON.stringify(envelope));fs.fsyncSync(fd);}finally{fs.closeSync(fd);}if(fs.existsSync(file))throw Error('SAFE_RECEIPT');fs.renameSync(pending,file);}
function read(directory,binding){if(!bindingValid(binding))throw Error('SAFE_RECEIPT');const file=path.join(directory,'controller-receipt.json');if(fs.existsSync(file+'.pending')||fs.lstatSync(file).isSymbolicLink()||fs.statSync(file).size>16384)throw Error('SAFE_RECEIPT');const e=JSON.parse(fs.readFileSync(file,'utf8'));if(!exact(e,['schemaVersion','binding','receipt','digest'])||e.schemaVersion!==1||!bindingValid(e.binding)||JSON.stringify(e.binding)!==JSON.stringify(binding)||!valid(e.receipt)||e.digest!==hash(e.receipt))throw Error('SAFE_RECEIPT');return e.receipt;}
module.exports={STAGES,ROLES,COUNTS,FAILURES,empty,valid,passed,advance,fail,publish,read,bindingValid};
