import fs from 'node:fs';import path from 'node:path';import {EventEmitter} from 'node:events';import {createRequire} from 'node:module';
import {afterEach,describe,expect,it,vi} from 'vitest';
const require=createRequire(import.meta.url),S=require('../../../tests/recovery/authorization-startup.cjs'),P=require('../../../tests/recovery/authorization-window-protocol.cjs'),W=require('../../../tests/recovery/authorization-window.cjs');
const Q=require('../../../tests/recovery/window-predicates.cjs');
const predicates=(old:any)=>{const q=Q.proof();q.predicates.processIdentity=old.helper?'passed':'failed';q.predicates.ownerMatches=old.window?'passed':'failed';q.predicates.foreground=old.foreground?'passed':'failed';return q;};
afterEach(()=>{vi.restoreAllMocks();vi.useRealTimers();});
const redacted=(r:any)=>{expect(P.valid(r)).toBe(true);expect(JSON.stringify(r)).not.toMatch(/secret|CRASH-B-|nonce|\"pid\"|\"handle\"|\"path\"|stack|Authorization|[A-Z]:\\\\/);};
function fake(script:(x:any)=>void){
 const child:any=new EventEmitter();const emit=child.emit.bind(child);child.emit=(event:string,...args:any[])=>{const r=emit(event,...args);if(event==='exit')queueMicrotask(()=>emit('close',...args));return r;};child.pid=90102;child.stdout=new EventEmitter();child.stderr=new EventEmitter();child.stdin=new EventEmitter();const socket:any=new EventEmitter();let c:any,ended=false;
 const exit=(code=0)=>{if(ended)return;ended=true;child.emit('exit',code);};
 child.stdin.end=vi.fn(()=>queueMicrotask(()=>exit(0)));
 child.stdin.write=(init:Buffer)=>{c={scenario:'B',nonce:Buffer.from(init.subarray(8,24)),owner:Buffer.from(init.subarray(24,40)),instance:Buffer.from(init.subarray(40,56))};queueMicrotask(()=>{child.emit('spawn');script({child,exit,ctx:c,stage:(n:number,category=0)=>{const b=P.frame('S',c,n);b[7]=category;child.stdout.emit('data',b);},ready:()=>{const b=P.frame('R',c);b.writeUInt32LE(child.pid,56);b.writeUInt32LE(process.pid,80);child.stdout.emit('data',b);}});});};
 socket.destroy=vi.fn();socket.write=(b:Buffer)=>{if(b[3]===72)queueMicrotask(()=>{const v=P.frame('V',c);v.fill(1,56,63);child.stdout.emit('data',v);const d=P.frame('M',c,1);d[7]=7;socket.emit('data',d);});else if(b[3]===65)queueMicrotask(()=>{socket.emit('end');exit();});};
 const dependencies={start:vi.fn(()=>child),verify:vi.fn(async()=>Q.proof()),connect:vi.fn(()=>{queueMicrotask(()=>socket.emit('connect'));return socket;})};return {child,dependencies,socket};
}
function ready(x:any){for(let n=5;n<=17;n++)x.stage(n);x.ready();}
describe('H12 bounded startup receipts',()=>{
 it.each([['bootstrap_error',5,20],['compiler_error',6,21],['helper_load_error',7,25],['argument_error',8,22],['parent_validation_error',9,22],['pipe_create_error',10,23],['sta_error',11,24],['winforms_error',12,24],['form_create_error',13,24],['message_loop_error',14,24],['readiness_error',16,24]])('preserves %s and last successful stage',async(category,stage,code)=>{const f=fake(x=>{for(let n=5;n<=Number(stage);n++)x.stage(n);x.stage(Number(stage),S.CATEGORIES.indexOf(category)+1);x.exit(code);});const r=await W.authorize({dependencies:f.dependencies});expect(r.failureCategory).toBe(category);expect(r.lastReachedStage).toBe(S.STAGES[Number(stage)-1]);expect(r.firstFailure).toMatchObject({actual:category,stage:r.lastReachedStage});expect(r.processCreated).toBe(true);redacted(r);});
 it('spawn rejection proves no OS process creation',async()=>{const f=fake(()=>{});f.dependencies.start.mockImplementation(()=>{throw Error('secret');});const r=await W.authorize({dependencies:f.dependencies});expect(r).toMatchObject({processCreated:false,lastReachedStage:'spawn_attempted',failureCategory:'spawn_error'});redacted(r);});
 it('asynchronous spawn error is distinct from exit',async()=>{const f=fake(()=>{});f.child.stdin.write=()=>queueMicrotask(()=>f.child.emit('error',Error('secret')));const r=await W.authorize({dependencies:f.dependencies});expect(r.processCreated).toBe(false);expect(r.failureCategory).toBe('spawn_error');});
 it('stderr does not close input; later compiler receipt wins',async()=>{const f=fake(x=>{x.stage(5);x.child.stderr.emit('data',Buffer.from('secret stderr'));expect(x.child.stdin.end).not.toHaveBeenCalled();x.stage(6);x.stage(6,3);x.exit(21);});const r=await W.authorize({dependencies:f.dependencies});expect(r).toMatchObject({stderrObserved:true,failureCategory:'compiler_error',safeExitClassification:'compile_failed'});redacted(r);});
 it('unclassified stderr cannot produce PASS even with complete readiness',async()=>{const f=fake(x=>{x.child.stderr.emit('data',Buffer.from('secret'));ready(x);});const r=await W.authorize({dependencies:f.dependencies});expect(r.result).not.toBe('granted');expect(r.failureCategory).toBe('stderr_observed');});
 it('safe nonzero exit category outranks stderr',async()=>{const f=fake(x=>{x.stage(5);x.child.stderr.emit('data',Buffer.from('secret'));x.exit(21);});const r=await W.authorize({dependencies:f.dependencies});expect(r.failureCategory).toBe('compiler_error');expect(r.safeExitClassification).toBe('compile_failed');});
 it('drains the final compiler receipt after exit before publishing',async()=>{const f=fake(x=>{x.stage(5);x.stage(6);x.exit(21);x.stage(6,3);});const r=await W.authorize({dependencies:f.dependencies});expect(r.failureCategory).toBe('compiler_error');expect(r.lastReachedStage).toBe('compiler_started');});
 it('OS exit does not misclassify a final fragmented receipt',async()=>{const f=fake(x=>{x.stage(5);x.stage(6);const b=P.frame('S',x.ctx,6);b[7]=3;x.child.stdout.emit('data',b.subarray(0,20));x.exit(21);x.child.stdout.emit('data',b.subarray(20));});const r=await W.authorize({dependencies:f.dependencies});expect(r.failureCategory).toBe('compiler_error');});
 it('late stderr before stdio close revokes provisional success',async()=>{const f=fake(ready);f.child.on('exit',()=>queueMicrotask(()=>f.child.stderr.emit('data',Buffer.from('secret'))));const r=await W.authorize({dependencies:f.dependencies});expect(r.result).not.toBe('granted');expect(r.stderrObserved).toBe(true);expect(r.failureCategory).toBe('stderr_observed');redacted(r);});
 it('unexpected exit is classified without retaining the raw code',async()=>{const f=fake(x=>{x.stage(5);x.exit(987654);});const r=await W.authorize({dependencies:f.dependencies});expect(r).toMatchObject({failureCategory:'unexpected_exit',safeExitClassification:'unexpected_exit'});redacted(r);});
 it('EOF without a receipt stays EOF',async()=>{const f=fake(x=>x.child.stdout.emit('end'));expect((await W.authorize({dependencies:f.dependencies})).failureCategory).toBe('eof');});
 it('abort remains distinct from EOF used for shutdown',async()=>{const c=new AbortController(),f=fake(x=>{x.stage(5);c.abort();});expect((await W.authorize({dependencies:f.dependencies,signal:c.signal})).failureCategory).toBe('aborted');});
 it('readiness timeout is bounded and closes helper normally',async()=>{vi.useFakeTimers();const f=fake(x=>x.stage(5)),r=W.authorize({dependencies:f.dependencies});await vi.advanceTimersByTimeAsync(45000);expect((await r).failureCategory).toBe('timeout');expect(f.child.stdin.end).toHaveBeenCalledTimes(1);});
 it.each(['regression','duplicate','unknown_stage','unknown_category','foreign_binding','raw_field','unknown_frame','half_frame'])('rejects %s receipt',async(kind)=>{const f=fake(x=>{x.stage(5);const b=P.frame('S',x.ctx,6);if(kind==='regression')b[6]=4;if(kind==='duplicate')b[6]=5;if(kind==='unknown_stage')b[6]=255;if(kind==='unknown_category')b[7]=255;if(kind==='foreign_binding')b[8]^=1;if(kind==='raw_field')b[56]=1;if(kind==='unknown_frame')b[3]=255;x.child.stdout.emit('data',kind==='half_frame'?b.subarray(0,20):b);if(kind==='half_frame')x.child.stdout.emit('end');});const r=await W.authorize({dependencies:f.dependencies});expect(r).toMatchObject({result:'helper_exit',failureCategory:'readiness_error'});redacted(r);});
 it('complete fragments are consumed atomically and monotonically',async()=>{const f=fake(x=>{for(let n=5;n<=17;n++){const b=P.frame('S',x.ctx,n);x.child.stdout.emit('data',b.subarray(0,20));x.child.stdout.emit('data',b.subarray(20));}x.ready();});const r=await W.authorize({dependencies:f.dependencies});expect(r).toMatchObject({result:'granted',lastReachedStage:'terminal_exit',stageSequence:22,processCreated:true,readinessReceived:true,safeExitClassification:'success',firstFailure:null});redacted(r);});
 it('readiness cannot bypass missing startup receipts',async()=>{vi.useFakeTimers();const f=fake(x=>x.ready()),p=W.authorize({dependencies:f.dependencies});await vi.advanceTimersByTimeAsync(45000);expect((await p).result).not.toBe('granted');expect(f.dependencies.verify).not.toHaveBeenCalled();});
 it('independent identity rejection has identity category',async()=>{const f=fake(ready);f.dependencies.verify.mockResolvedValue(predicates({helper:false,window:false,foreground:false}));const r=await W.authorize({dependencies:f.dependencies});expect(r).toMatchObject({failureCategory:'helper_identity_failed',lastReachedStage:'identity_verification_started'});});
 it('pipe connect creation failure has pipe category',async()=>{const f=fake(ready);f.dependencies.connect.mockImplementation(()=>{throw Error('secret');});const r=await W.authorize({dependencies:f.dependencies});expect(r).toMatchObject({failureCategory:'pipe_connect_error',lastReachedStage:'identity_verification_completed'});});
 it.each(Object.entries(S.EXIT_MAP))('raw exit %s maps to a safe enum', (code,classification)=>expect(S.exitClass(Number(code))).toBe(classification));
 it('unknown exit and unsafe output rejected',()=>{expect(S.exitClass(null)).toBe('unknown_exit');expect(S.valid({...S.fields(),failureCategory:'secret'})).toBe(false);expect(P.valid({...P.initial(),...S.fields(),path:'secret'})).toBe(false);});
 it('bootstrap reports before compile; classifications and STA setup precede Form',()=>{const base=path.resolve('tests/recovery'),ps=fs.readFileSync(path.join(base,'authorization-window.ps1'),'utf8'),cs=fs.readFileSync(path.join(base,'authorization-window-helper.cs'),'utf8');expect(ps.indexOf('Write-StartupReceipt 5 0')).toBeLessThan(ps.indexOf('Add-Type'));expect(cs.indexOf('GetApartmentState')).toBeLessThan(cs.indexOf('Application.EnableVisualStyles'));expect(cs.indexOf('Application.SetUnhandledExceptionMode')).toBeLessThan(cs.indexOf('new AuthorizationForm'));expect(cs).toContain('Stage(15);Application.Run');expect(cs).toContain('Harness.Stage(16)');expect(cs).toContain('Harness.Stage(17)');});
});
