import fs from 'node:fs';import {createRequire} from 'node:module';import {afterEach,describe,expect,it,vi} from 'vitest';
const require=createRequire(import.meta.url),Q=require('../../../tests/recovery/window-predicates.cjs');
afterEach(()=>vi.useRealTimers());
const q=(change:any={})=>({predicates:{...Q.proof().predicates,...change},result:'passed'});
async function run(seq:any[]){vi.useFakeTimers();let i=0;const calls:number[]=[];const probe=vi.fn(async(_:any,o:any)=>{calls.push(o.timeoutMs);return seq[Math.min(i++,seq.length-1)];});const p=Q.stable(probe,null,{now:()=>Date.now()});await vi.advanceTimersByTimeAsync(5000);return {r:await p,probe,calls};}
describe('H14 independent predicates and bounded readiness',()=>{
 it('validates seven enum-only predicates and rejects arbitrary data',()=>{expect(Q.valid(q().predicates)).toBe(true);expect(Q.valid({...q().predicates,handle:3})).toBe(false);expect(Q.valid({...q().predicates,visible:true})).toBe(false);expect(Q.decode(Buffer.alloc(8)).result).toBe('window_query_error');expect(Q.decode(Buffer.from([1,1,1,1,1,2,1])).predicates.foreground).toBe('failed');});
 it('process proof survives later owner failure',()=>{const r:any={helperIdentityVerified:false};Q.project(r,q({ownerMatches:'failed'}),'readiness_verification');expect(r.helperIdentityVerified).toBe(true);expect(r.windowOwnerVerified).toBe(false);Q.project(r,Q.queryFail('window_query_error'),'readiness_verification');expect(r.helperIdentityVerified).toBe(true);});
 it.each([['isWindow','failed','window_handle_invalid'],['ownerQuerySucceeded','failed','owner_query_failed'],['ownerMatches','failed','owner_mismatch'],['visible','failed','window_not_visible'],['queryOutcome','unavailable','window_query_error']])('%s maps exactly', (key,value,result)=>expect(Q.failure(q({[key]:value}))).toBe(result));
 it('visibility recovers and requires three consecutive successes',async()=>{const {r}=await run([q({visible:'failed'}),q(),q(),q()]);expect(r.result).toBe('passed');expect(r.samples).toBe(4);});
 it('persistent hidden window fails within 5s with exact cause',async()=>{const {r,calls}=await run([q({visible:'failed'})]);expect(r.result).toBe('window_not_visible');expect(calls.every((v:number)=>v>0&&v<=5000)).toBe(true);expect(r.samples).toBeLessThanOrEqual(34);});
 it('two zero-failure samples never count as three',async()=>{const {r}=await run([q(),q(),q({visible:'failed'})]);expect(r.result).toBe('window_not_visible');});
 it('a failed middle sample resets stable count',async()=>{const {r}=await run([q(),q(),q({visible:'failed'}),q(),q(),q()]);expect(r.result).toBe('passed');expect(r.samples).toBe(6);});
 it('initial invalid handle may settle but cannot bypass three samples',async()=>{const {r}=await run([q({isWindow:'failed'}),q(),q(),q()]);expect(r.result).toBe('passed');expect(r.samples).toBe(4);});
 it('readiness never requires foreground',async()=>{const {r}=await run([q({foreground:'failed'})]);expect(r.result).toBe('passed');expect(r.samples).toBe(3);});
 it('click phase always requires foreground',()=>{expect(Q.failure(q({foreground:'failed'}),true)).toBe('helper_not_foreground');expect(Q.failure(q(),true)).toBe(null);});
 it('query error is not window visibility failure',async()=>{const {r}=await run([Q.queryFail('window_query_error')]);expect(r.result).toBe('window_query_error');expect(r.samples).toBe(1);});
 it('hanging query is aborted at remaining deadline',async()=>{vi.useFakeTimers();let aborted=false;const p=Q.stable(async(_:any,o:any)=>{o.signal.addEventListener('abort',()=>{aborted=true;});return new Promise(()=>{});},null,{now:()=>Date.now()});await vi.advanceTimersByTimeAsync(5000);expect((await p).result).toBe('window_query_timeout');expect(aborted).toBe(true);});
 it('sampling interval is 150ms and query timeout uses remaining total',async()=>{vi.useFakeTimers();const times:number[]=[],budgets:number[]=[];const p=Q.stable(async(_:any,o:any)=>{times.push(Date.now());budgets.push(o.timeoutMs);return q();},null,{now:()=>Date.now()});await vi.advanceTimersByTimeAsync(500);expect((await p).result).toBe('passed');expect(times[1]-times[0]).toBe(150);expect(times[2]-times[1]).toBe(150);expect(budgets).toEqual([5000,4850,4700]);});
 it('explicit show runs on UI thread, uses current work area, and never invokes authorization',()=>{const cs=fs.readFileSync('tests/recovery/authorization-window-helper.cs','utf8');expect(cs).toContain('BeginInvoke(new Action');expect(cs).toContain('Screen.FromPoint(Cursor.Position).WorkingArea');expect(cs).toContain('Visible=true;Harness.ShowWindow(Handle,1);Show();Activate();BringToFront();cancel.Focus();');const shown=cs.slice(cs.indexOf('Shown+='),cs.indexOf('timer.Interval='));expect(shown).not.toContain('Choose(1)');expect(cs).toContain('AcceptButton=null');expect(cs).toContain('Application.Run(form)');expect(cs).not.toMatch(/SendInput|SendKeys|PostMessage|RegisterHotKey/);});
 it('hidden console strategy is paired with explicit native Form show',()=>{const js=fs.readFileSync('tests/recovery/authorization-window.cjs','utf8'),cs=fs.readFileSync('tests/recovery/authorization-window-helper.cs','utf8');expect(js).toContain('windowsHide:true');expect(cs).toContain('Harness.ShowWindow(Handle,1)');});
});
