import {createRequire} from 'node:module';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {afterEach,describe,it,expect,vi} from 'vitest';
const require=createRequire(import.meta.url),E=require('../../../tests/recovery/controller-engine.cjs'),R=require('../../../tests/recovery/controller-receipt.cjs');
const dirs:string[]=[];afterEach(()=>{vi.restoreAllMocks();vi.useRealTimers();for(const d of dirs.splice(0)){if(path.dirname(d)!==fs.realpathSync.native(os.tmpdir())||!path.basename(d).startsWith('controller-unit-'))throw Error();fs.rmSync(d,{recursive:true});}});
function fixture(){let time=0;const actions:string[]=[],binding={scenario:'controller_selftest',owner:'a'.repeat(32),launch:'b'.repeat(32)};
 const driver:any={open:vi.fn(async()=>({identityVerified:true,handlesOpened:true,protectedVerified:true})),state:vi.fn(async(t:number)=>{actions.push('state'+t);return false;}),kill:vi.fn(async(t:number)=>{actions.push('kill'+t);return 'returned';}),wait:vi.fn(async(t:number)=>{actions.push('wait'+t);return true;}),descendants:vi.fn(async()=>({descendants:0,residualTokens:[]})),protected:vi.fn(async()=>true),close:vi.fn(async()=>{})};
 const o:any={binding,entries:R.ROLES.map((role:string,token:number)=>({role,token})),driver,now:()=>time,publish:vi.fn(async()=>{}),beforeDispatch:vi.fn(async()=>{}),markDispatch:vi.fn()};return {o,driver,actions,setTime:(n:number)=>{time=n;}};}
const safe=(r:any)=>{expect(R.valid(r)).toBe(true);expect(JSON.stringify(r)).not.toMatch(/"pid"|"parent"|"nonce"|"handle"|"path"|creation|raw|stack|secret|[A-Z]:\\/i);};
describe('H17 shared controller algorithm, fake pinned handles only',()=>{
 it('signals Main then waits, then CoreHost then waits, then children and waits',async()=>{const {o,actions}=fixture(),r=await E.run(o);expect(r.verified).toBe(true);expect(actions).toEqual(['state0','kill0','wait0','state1','kill1','wait1','state2','kill2','state3','kill3','wait2','wait3']);safe(r.receipt);});
 it('Kill returned does not prove exit; timeout fails but safely processes remaining pinned handles',async()=>{const {o,driver}=fixture();driver.wait.mockImplementation(async(t:number)=>t!==0);const r=await E.run(o);expect(r.verified).toBe(false);expect(r.executed).toBe(true);expect(driver.kill).toHaveBeenCalledTimes(4);expect(r.receipt.primaryFailure).toEqual({category:'exit_wait_timeout',stage:'main_exit_waited'});expect(r.receipt.roleCounters.main).toMatchObject({killReturned:1,exitObserved:0,waitTimedOut:1});});
 it('already exited handles are waited and never signalled',async()=>{const {o,driver}=fixture();driver.state.mockResolvedValue(true);const r=await E.run(o);expect(r.verified).toBe(true);expect(driver.kill).not.toHaveBeenCalled();expect(driver.wait).toHaveBeenCalledTimes(4);expect(r.receipt.roleCounters.main.alreadyExited).toBe(1);});
 it.each([['state','handle_state_failed','handleError'],['kill','kill_call_failed','killError'],['wait','handle_state_failed','handleError']])('classifies %s error and retains other target cleanup',async(op,category,count)=>{const {o,driver}=fixture();driver[op].mockRejectedValueOnce(Error('secret'));const r=await E.run(o);expect(r.receipt.primaryFailure.category).toBe(category);expect(r.receipt.roleCounters.main[count]).toBe(1);expect(driver.wait.mock.calls.some((c:any)=>c[0]===3)).toBe(true);safe(r.receipt);});
 it.each(['pre_kill_identity_failed','handle_open_failed','protected_baseline_failed','target_set_incomplete'])('pre-dispatch %s never kills',async category=>{const {o,driver}=fixture();driver.open.mockRejectedValue({category});const r=await E.run(o);expect(r.receipt.primaryFailure.category).toBe(category);expect(driver.kill).not.toHaveBeenCalled();});
 it('retains primary error when descendant/protected/cleanup checks also fail',async()=>{const {o,driver}=fixture();driver.kill.mockRejectedValueOnce(Error());driver.descendants.mockRejectedValue(Error());driver.protected.mockResolvedValue(false);const r=await E.run(o);expect(r.receipt.primaryFailure.category).toBe('kill_call_failed');expect(r.receipt.cleanupOutcome).toBe('completed');expect(r.verified).toBe(false);});
 it.each([['descendants','descendant_query_failed'],['protected','protected_process_missing']])('classifies %s query failure',async(op,category)=>{const {o,driver}=fixture();driver[op].mockRejectedValue(Error());expect((await E.run(o)).receipt.primaryFailure.category).toBe(category);});
 it('detects matching residual and unknown descendants without expanding handles',async()=>{const {o,driver}=fixture();driver.descendants.mockResolvedValue({descendants:1,residualTokens:[2]});const r=await E.run(o);expect(r.receipt.roleCounters.renderer.residualMatching).toBe(1);expect(r.verified).toBe(false);expect(driver.open).toHaveBeenCalledOnce();expect(driver.kill.mock.calls.map((c:any)=>c[0])).toEqual([0,1,2,3]);});
 it('missing protected sentinel fails while preserving successful termination facts',async()=>{const {o,driver}=fixture();driver.protected.mockResolvedValue(false);const r=await E.run(o);expect(r.receipt.allTargetsExited).toBe(true);expect(r.receipt.primaryFailure.category).toBe('protected_process_missing');});
 it('total monotonic deadline prevents further calls',async()=>{const {o,driver,setTime}=fixture();driver.wait.mockImplementationOnce(async()=>{setTime(15000);return true;});const r=await E.run(o);expect(r.receipt.primaryFailure.category).toBe('controller_budget_exhausted');expect(driver.kill).toHaveBeenCalledTimes(1);expect(r.receipt.totalDurationBucket).toBe('deadline_reached');});
 it('hung query is bounded',async()=>{vi.useFakeTimers();const {o,driver}=fixture();driver.open.mockImplementation(()=>new Promise(()=>{}));const p=E.run(o);await vi.advanceTimersByTimeAsync(3001);const r=await p;expect(r.verified).toBe(false);expect(driver.kill).not.toHaveBeenCalled();});
 it('final guard failure cannot signal any fixed handle',async()=>{const {o,driver}=fixture();o.beforeDispatch.mockRejectedValue(Error());const r=await E.run(o);expect(r.executed).toBe(false);expect(driver.kill).not.toHaveBeenCalled();});
 it.each([0,33])('rejects invalid target count %s',async n=>{const {o,driver}=fixture();o.entries=Array.from({length:n},(_,token)=>({token,role:'main'}));expect((await E.run(o)).verified).toBe(false);expect(driver.open).not.toHaveBeenCalled();});
 it('receipt write failure retains already performed side effect',async()=>{const {o}=fixture();o.publish.mockRejectedValue(Error());const r=await E.run(o);expect(r.executed).toBe(true);expect(r.receiptPublished).toBe(false);expect(r.receipt.primaryFailure.category).toBe('receipt_write_failed');expect(r.receipt.lastReachedStage).toBe('protected_postcheck_completed');});
 it('partial handle-open receipt keeps exact startup counters',async()=>{const {o,driver}=fixture();const startupCounts=Object.fromEntries(R.ROLES.map((role:string,i:number)=>[role,{identityVerified:1,handleOpened:i<2?1:0,handleError:i===2?1:0,identityUnavailable:0}]));driver.open.mockRejectedValue({category:'handle_open_failed',startupCounts});const r=await E.run(o);expect(r.receipt.lastReachedStage).toBe('pre_kill_identity_verified');expect(r.receipt.roleCounters.corehost.handleOpened).toBe(1);expect(r.receipt.roleCounters.renderer.handleOpened).toBe(0);expect(r.receipt.roleCounters.renderer.handleError).toBe(1);expect(driver.kill).not.toHaveBeenCalled();});
 it('strict receipt cannot claim success with zero or contradictory target counts',()=>{const r=require('../../../tests/recovery/controller-fixture.cjs').success().receipt;r.roleCounters.main.exitObserved=0;expect(R.passed(r)).toBe(false);});
 it('all fixed failure categories remain bounded',()=>{for(const category of R.FAILURES){const r=R.empty();R.fail(r,category);R.fail(r,'unexpected_controller_error');expect(r.primaryFailure.category).toBe(category);safe(r);}});
 it('stages never regress',()=>{const r=R.empty();for(const stage of R.STAGES)R.advance(r,stage);expect(()=>R.advance(r,R.STAGES[0])).toThrow();});
 it.each([-1,17,1.5,'1'])('rejects unbounded role count %s',value=>{const r=R.empty();r.roleCounters.main.resolved=value;expect(R.valid(r)).toBe(false);});
});
describe('H17 immutable receipt and ownership',()=>{
 function setup(){const dir=fs.mkdtempSync(path.join(fs.realpathSync.native(os.tmpdir()),'controller-unit-'));dirs.push(dir);return {dir,binding:fixture().o.binding,receipt:require('../../../tests/recovery/controller-fixture.cjs').success().receipt};}
 it('atomically publishes and reads one launch-bound receipt',()=>{const {dir,binding,receipt}=setup();R.publish(dir,binding,receipt);expect(R.read(dir,binding)).toEqual(receipt);expect(()=>R.publish(dir,binding,receipt)).toThrow();});
 it.each(['missing','pending','malformed','version','owner','launch','scenario','extra'])('fails closed on %s receipt',kind=>{const {dir,binding,receipt}=setup();const f=path.join(dir,'controller-receipt.json');if(kind!=='missing')R.publish(dir,binding,receipt);if(kind==='pending')fs.writeFileSync(f+'.pending','{');if(kind==='malformed')fs.writeFileSync(f,'{');if(['version','owner','launch','scenario','extra'].includes(kind)){const e=JSON.parse(fs.readFileSync(f,'utf8'));if(kind==='version')e.schemaVersion=2;else if(kind==='extra')e.identity='secret';else e.binding[kind]=kind==='scenario'?'B':'c'.repeat(32);fs.writeFileSync(f,JSON.stringify(e));}expect(()=>R.read(dir,binding)).toThrow();});
});
describe('H17 backend and protection source contracts',()=>{
 it.each(['parent','sentinel','helper','reused','missing','wrong_owner'])('private target guard rejects %s without starting transport',kind=>{const S=require('../../../tests/recovery/controller-session.cjs');const parent={pid:100},sentinel={pid:101,parent:100};const e:any={pid:102,parent:100,created:'synthetic',executable:'node.exe',role:'main',nonce:'a'.repeat(32)};const rows=[{...e}];if(kind==='parent')e.pid=100;if(kind==='sentinel')e.pid=101;if(kind==='helper')e.role='helper';if(kind==='reused')rows[0].created='different';if(kind==='missing')rows.length=0;if(kind==='wrong_owner')e.nonce='b'.repeat(32);expect(()=>S.validateTargets([e],rows,parent,sentinel,'B','a'.repeat(32))).toThrow();});
 it('protected sentinel remains outside the only fixed termination tokens',()=>{const S=require('../../../tests/recovery/controller-session.cjs');const parent={pid:100},sentinel={pid:101,parent:100};const entries=[{pid:102,parent:100,created:'synthetic',executable:'node.exe',role:'main',nonce:'a'.repeat(32)}];expect(()=>S.validateTargets(entries,entries,parent,sentinel,'B','a'.repeat(32))).not.toThrow();});
 it('pins handles once, never signals query results, excludes parent/sentinel, waits explicitly',()=>{const s=fs.readFileSync('tests/recovery/crash-controller.ps1','utf8');expect(s).toContain('$proc.Handle');expect(s).toContain('$pinned.Kill()');expect(s).toContain('$pinned.WaitForExit');expect(s).toContain('$spec.sentinel.pid');expect(s).toContain('$spec.parent.pid');expect(s).not.toMatch(/taskkill|Stop-Process|Kill\(\$true\)/);const after=s.slice(s.indexOf('while ($null'));expect(after).not.toContain('GetProcessById');});
 it('selftest cannot import app, recovery or provider and only fixed workers are sacrificial',()=>{const s=fs.readFileSync('tests/recovery/controller-selftest.cjs','utf8');expect(s).toContain("spawnWorker('sacrificial'");expect(s).not.toMatch(/electron|Notepad|State\.seed|P\.create|provider\./);expect(s).toContain('zeros===3');const w=fs.readFileSync('tests/recovery/controller-worker.cjs','utf8');expect(w).toContain("line==='shutdown'");expect(w).not.toMatch(/kill\(|spawn\(|fetch\(/);});
});
